sudo: false
language: rust

matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly
      name: Stable compiletest
    - rust: nightly
      name: Unstable compiletest
      env: FEATURES="unstable" TEST_FEATURES="unstable"
    - rust: nightly
      name: Minimal versions
      before_script:
        - cargo update -Z minimal-versions

script:
  - cargo build --features "${FEATURES:-}"
  - cargo clean
  - cargo test --features "${FEATURES:-}"
  - cargo clean
  - cargo test --features "${TEST_FEATURES:-}" --manifest-path tests/Cargo.toml
