[package]
name = "indoc"
version = "0.3.1" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
documentation = "https://github.com/dtolnay/indoc"
keywords = ["heredoc", "nowdoc", "multiline", "string", "literal"]
readme = "README.md"

[features]
unstable = ["indoc-impl/unstable"]

[dependencies]
indoc-impl = { version = "0.3.1", path = "impl" }
proc-macro-hack = "0.5.3"

[workspace]
members = ["impl", "tests", "unindent"]

[badges]
travis-ci = { repository = "dtolnay/indoc" }
